# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c07f1b506ae45741e7b938429848349a97f056d5e5c3606bf09f1e15c3a9b3e744840048300d8b25c46ec4e74d3f4dcb19bbe9f2a71761c0ae64051d0c2913eb

test:
  secret_key_base: e2ac8a4db69a2acff32e9d1a8308917174c2ff0fbb728eec1c32940fdf57d918438fb860f7398404ce4466e19b5aa86f8156a8f39421f28e61fc1b4f5b7b44a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
